name: 'Send matrix message'
description: 'Submit message to a matrix-hookshot webhook server'
inputs:
  github_token:
    description: Github token to work with
    required: true
  text_template:
    description: Fallback text template to render
    required: true
  html_template:
    description: HTML template to render
    required: true
  matrix_access_token:
    description: Matrix access token
    required: false
  matrix_room_id:
    description: Matrix room ID
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
