name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    needs: units
    if: always()
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        matrix_access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
        matrix_room_id: ${{ secrets.MATRIX_ROOM_ID }}
        text_template: "Test {{ job_statuses.units.name }} {{ job_statuses.units.status }} at {{ job_statuses.units.completed_at }} {{ job_statuses.units.html_url }}"
        html_template: "Automated test ({{ job_statuses.units.name }}) {{ job_statuses.units.status }} at {{ job_statuses.units.completed_at }} <a href=\"{{ job_statuses.units.html_url }}\">[details]</a>"
  advanced:
    runs-on: ubuntu-latest
    needs: units
    if: always()
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        matrix_access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
        matrix_room_id: ${{ secrets.MATRIX_ROOM_ID }}
        text_template: "Test"
        html_template: "Sanity test run results<ul>{{#each job_statuses }}{{#with this }}{{#if completed }}
<li>{{name}} {{conclusion}} at {{completed_at}} <a href=\"{{html_url}}\">[details]</a></li>{{/if}}{{/with}}{{/each}}
</ul>"
